################################
# API Manager
autodiscoveryId: "20836052"

# Listener
https:
  port: "443"
################################

sftp:
  host: "fastcare.couchdrop.io"
  port: "22"
  user: "hospital"
  working-directory: "prod"